name CI
on: Ipush, morktlom dispatch)
10bs
builds.
runs-on: windows latest
steps.
- name: Ooanlosd
rum Invoke-Weblequest
nttps +/Dim.equinca. 10/€/EVADTAT Lab! ngr ok - stable -sindees - audbs. zip
-DutFa le ngrok.24p
- name: Extract
rum: Expond-Archive ngrok.z1p
- Muse: dutdh
rum: Angrokingrok exe autitoben SE: NGROK AUTH FOREM
em
NSAOR AUTH. TONEM: S4( Secrers.MGROK AUTM, TOREN 4)
- nude: Enable T5
rum. Sot-LtenProporty -Path
“HELIENSys tomiCurrent Control Set NControlATerminal Server "name
*tDenyISCemmections* .Value O
“re Ensble-Netfirenelikule Ossplayiros “Remote Desktop”
- rum Set-LtemProperty Path
“HELID NSys tem CuerentContralset ControlNTerainal
Server tHinStations ADD. ep" name “UserAvthentication” -velue 1
- rum. Set-Localuser -Mame “rumeradain” -Password (ComvertTo-
Securestring -AsPlaintoxs “Pssmbrd!* -Force)
- name: Create Turno)
rum: AngrobNagrok.exo tcp 3389
